### PR TITLE
Set influxdb version and add influx to readme, Support for config in docker

### PR DESCRIPTION
**Pull request by horviskoadrianko**
Set version of influxdb
Prompt user to change localhost to influx when using docker
#3 fixes this
#1 maybe will fix this
Add support for config files in docker

### CODE REVIEW

**Comment by horviskoadrianko** [comment]
This is not the best way to implement this but works

**Comment by Tucsky** [comment]
I wouldn't know, I don't have docker

**Comment by adeacetis** [comment]
@eYdr1en Reading back two years later. I ran into the same issues as you.
Could you please review this PR? I am interested in your opinion on what would be a better implementation if you have the time of course.
https://github.com/Tucsky/aggr-server/pull/18

**Comment by eYdr1en** [comment]
@adeacetis Sorry for my late comment. I just didn't like how I've implemented config variables as you would firstly need to set `CONFIG_BOL` to `1` and also `CONFIG` to `config name`. There is probably a way to only use `CONFIG` variable.

**Pull request closed without merging**
